[package]
name = "JoshRayFirstRustHW"
version = "0.1.0"
authors = ["jraypdx <44383003+jraypdx@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
